CREATE DATABASE IF NOT EXISTS guestbook_db
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE guestbook_db;

CREATE TABLE IF NOT EXISTS messages (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  content TEXT NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
